org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.workers.max=4
kotlin.incremental=true
kotlin.incremental.android=true
kotlin.parallel.tasks.in.project=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
